#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

export PATH="$PATH:/opt/nvim-linux64/bin"

export PYTHONPATH="${PYTHONPATH}:/home/christovis/productiontradetool/PreProcProdcom"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Monitor Settings
alias dualup='xrandr --auto --output HDMI2 --mode 1920x1080 --rate 75 --above eDP1'
alias dualleft='xrandr --auto --output HDMI2 --mode 1920x1080 --rate 75 --left-of eDP1'
alias dualright='xrandr --auto --output HDMI2 --mode 1920x1080 --rate 75 --right-of eDP1'
alias singlemonitor='xrandr --auto --output HDMI2 --off'
alias screenonly='xrandr --auto --output eDP1 --off'
alias cosmaa='ssh -Y dc-beck3@login5a.cosma.dur.ac.uk'

# SSH: activate keys
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/github_id_ed25519

# Quarto: An open-source scientific and technical publishing system
alias quarto='~/opt/quarto-1.5.57/bin/quarto'

# Miniconda: A free, miniature installation of Anaconda Distribution
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/christovis/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/christovis/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/christovis/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/christovis/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

